config/routes.rb
SampleApp::Application.routes.draw do
  resources :password_reminders, :only => [:new, :create] do
    get :reset, :on => :member
  end

  resources :direct_messages, :only => [] do
    get :received, :on => :collection
    get :sent, :on => :collection
  end

  resources :users do
    member do
      get :following, :followers, :confirm, :feed
    end
    resources :feeds, :only => [] do
      get :private, :on => :member
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/recover_password', :to => 'password_reminders#new'
  match '/signup',           :to => 'users#new'
  match '/signin',           :to => 'sessions#new'
  match '/signout',          :to => 'sessions#destroy'
  match '/contact',          :to => 'pages#contact'
  match '/about',            :to => 'pages#about'
  match '/help',             :to => 'pages#help'

  root :to => 'pages#home'

end

app/models/direct_message.rb
class DirectMessage < ActiveRecord::Base
  belongs_to :sender, :class_name => User.name
  belongs_to :recipient, :class_name => User.name
  
  validates :content, :presence => true
  validates :sender, :presence => true
  validates :recipient, :presence => true
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController
  def sent
    @direct_messages = DirectMessage.where(["sender_id = ?", current_user])
  end

  def received
    @direct_messages = DirectMessage.where(["recipient_id = ?", current_user])
  end

end

app/views/direct_messages/_menu.html.haml
/BEGIN direct_messages/_menu.html.haml

%nav.submenu
  %ul
    %li.round
      = link_to_unless_current "Received Items", received_direct_messages_path
    %li.round
      = link_to_unless_current "Sent Items", sent_direct_messages_path

%p.instructions
  To send a direct message, prepend your micropost with the lowercase letter d
  followed by the recipient's username. For example, given a valid user with
  username "kenneth", you can post:
  %span.center "d kenneth this is a sample direct (i.e. private) message"
  = link_to "Click here", root_path
  to send a direct message.

/END direct_messages/_menu.html.haml

app/views/direct_messages/received.html.haml
/BEGIN direct_messages/received.html.haml

= render :partial => 'menu'

- if @direct_messages
  %table.microposts
    - @direct_messages.each do |dm|
      %tr
        %td.gravatar
          = link_to gravatar_for(dm.sender), dm.sender

        %td.micropost
          %span.user= link_to dm.sender.username, dm.sender
          %span.content= dm.content
          %span.timestamp
            = time_ago_in_words(dm.created_at)
            ago.

/END direct_messages/received.html.haml

app/views/direct_messages/sent.html.haml
/BEGIN direct_messages/sent.html.haml

= render :partial => 'menu'

- if @direct_messages
  %table.microposts
    - @direct_messages.each do |dm|
      %tr
        %td.gravatar
          = link_to gravatar_for(dm.recipient), dm.recipient

        %td.micropost
          %span.user= link_to dm.recipient.username, dm.recipient
          %span.content= dm.content
          %span.timestamp
            = time_ago_in_words(dm.created_at)
            ago.

/END direct_messages/sent.html.haml