config/routes.rb
SampleApp::Application.routes.draw do
  resources :password_reminders, :only => [:new, :create] do
    get :reset, :on => :member
  end

  resources :direct_messages, :only => [] do
    get :received, :on => :collection
    get :sent, :on => :collection
  end

  resources :users do
    member do
      get :following, :followers, :confirm, :feed
    end
    resources :feeds, :only => [] do
      get :private, :on => :member
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/recover_password', :to => 'password_reminders#new'
  match '/signup',           :to => 'users#new'
  match '/signin',           :to => 'sessions#new'
  match '/signout',          :to => 'sessions#destroy'
  match '/contact',          :to => 'pages#contact'
  match '/about',            :to => 'pages#about'
  match '/help',             :to => 'pages#help'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20101125131527
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean
#

class User < ActiveRecord::Base
    include ActiveRecord::Transitions
    
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :username

  has_many :microposts, :dependent => :destroy
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  has_many :replies, :class_name => 'Recipient', :dependent => :destroy
  has_many :received_replies, :through => :replies, :source => 'micropost'

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  uname_regex = /^[a-z](\w*[a-z0-9])*$/i

  validates :name, :presence => true,
                   :length   => { :maximum => 50 }

  validates :username, :presence   => true,
                       :length     => { :maximum => 15 },
                       :format     => { :with => uname_regex },
                       :uniqueness => { :case_sensitive => false }

  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 },
                       :unless       => :password_is_not_being_updated?

  before_save :encrypt_password

  state_machine do
    state :inactive
    state :active

    event :activate do
      transitions :to => :active, :from => :inactive
    end
  end

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def following?(followed)
    relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end

  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end

  def feed
    Micropost.from_users_followed_by(self)
  end

  def to_param
    self.username
  end

  private

    def encrypt_password
      unless password_is_not_being_updated?
        self.salt = make_salt
        self.encrypted_password = encrypt(password)
      end
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

    def password_is_not_being_updated?
      self.id && self.password.blank?
    end
end

app/controllers/users_controller.rb
require 'crypto'

class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create, :confirm, :feed]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find_by_username(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name

    respond_to do |extension|
      extension.html
      extension.rss { render :layout => false }
    end
  end

  def new
    @user = User.new
    @title = "Sign up"
  end

  def edit
    @title = "Edit user"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.signup_confirmation(:host => request.env['HTTP_HOST'],
        :token => Crypto.encrypt("#{@user.id}"), :email => @user.email).deliver
      flash[:notice] = "To complete registration, please check your email."
      redirect_to root_url
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @user = User.find_by_username(params[:id])
    @title = "Edit user"
  end

  def update
    @user = User.find_by_username(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    User.find_by_username(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find_by_username(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find_by_username(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end

  def confirm
    begin
      user = User.find( Crypto.decrypt(params[:id]) )
      user.activate!
      sign_in( user )
      flash[:success] = "Account confirmed. Welcome #{user.name}!"
      redirect_to root_url
    rescue Transitions::InvalidTransition
      sign_out if signed_in?
      flash[:notice] = "Account is already activated. Please sign in instead."
      redirect_to signin_path
    rescue
      flash[:error] = "Invalid confirmation token."
      redirect_to root_url
    end
  end

  def feed
    @user = User.find_by_username( params[:id] )
    @microposts = @user.microposts.limit(10)

    respond_to do |extension|
      extension.rss { render :layout => false}
    end
  end

  private

    def correct_user
      @user = User.find_by_username(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_follow.html.haml
/BEGIN users/_follow.html.haml

= form_for current_user.relationships.build(:followed_id => @user.id),
      :remote => true do |f|
  %div= f.hidden_field :followed_id
  .actions= f.submit "Follow"

/END users/_follow.html.haml

app/views/users/_follow_form.html.haml
/BEGIN users/_follow_form.html.haml

- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

/END users/_follow_form.html.haml

app/views/users/_unfollow.html.haml
/BEGIN users/_unfollow.html.haml

= form_for current_user.relationships.find_by_followed_id(@user),
      :html => { :method => :delete }, :remote => true do |f|
  .actions= f.submit "Unfollow"

/END users/_unfollow.html.haml

app/views/users/_user.html.haml
/BEGIN users/_user.html.haml

%li
  = gravatar_for user, :size => 30
  = link_to user.name, user
  - if current_user.admin?
    |
    = link_to "delete", user, :method => :delete, :confirm => "You sure?",
          :title => "Delete #{user.name}"

/END users/_user.html.haml

app/views/users/edit.html.haml
/BEGIN users/edit.html.haml

%h1 Edit user

= form_for(@user) do |f|
  = render 'shared/error_messages', :object => f.object

  .field
    = f.label :name
    %br/
    = f.text_field :name

  .field
    = f.label :email
    %br/
    = f.text_field :email

  .field
    = f.label :password
    %br/
    = f.password_field :password

  .field
    = f.label :password_confirmation, "Confirmation"
    %br/
    = f.password_field :password_confirmation

  .field
    = f.check_box :follower_notifications
    = f.label :follower_notifications, "Email me when someone starts following"

  .actions
    = f.submit "Update"

%div
  = gravatar_for @user
  %a{:href => "http://gravatar.com/emails"} change

/END users/edit.html.haml

app/views/users/index.html.haml
/BEGIN users/index.html.haml

%h1 All users

= will_paginate

%ul.users
  = render @users

= will_paginate

/END users/index.html.haml

app/views/users/new.html.haml
/BEGIN users/new.html.haml

%h1 Sign up

= form_for(@user) do |f|
  = render 'shared/error_messages', :object => f.object

  .field
    = f.label :name
    %br/
    = f.text_field :name

  .field
    = f.label :username
    %br/
    = f.text_field :username

  .field
    = f.label :email
    %br/
    = f.text_field :email

  .field
    = f.label :password
    %br/
    = f.password_field :password

  .field
    = f.label :password_confirmation, "Confirmation"
    %br/
    = f.password_field :password_confirmation

  .actions
    = f.submit "Sign up"

/END users/new.html.haml

app/views/users/show.html.haml
/BEGIN users/show.html.haml

%table.profile{:summary => "Profile information"}
  %tr
    %td.main
      %h1
        = gravatar_for @user
        = @user.name

      = render 'follow_form' if signed_in?

      - unless @user.microposts.empty?
        %table.microposts{:summary => "User microposts"}
          = render @microposts
        = will_paginate @microposts

    %td.sidebar.round
      %strong Name
      = @user.name
      %br/

      %strong URL
      = link_to user_path(@user), @user
      %br/

      %strong Microposts
      = @user.microposts.count

      = render 'shared/stats'
      = image_tag('feed.png', :alt => 'rss feed icon')
      = link_to "Subscribe", feed_user_path(@user, :format => :rss)

/END users/show.html.haml

app/views/users/show_follow.html.haml
/BEGIN users/show_follow.html.haml

%table{:summary => "Information about following/followers"}
  %tr
    %td.main
      %h1= @title

      - unless @users.empty?
        %ul.users
          = render @users
        = will_paginate @users

    %td.sidebar.round
      %strong Name
      = @user.name
      %br/

      %strong URL
      = link_to user_path(@user), @user
      %br/

      %strong Microposts
      = @user.microposts.count

      = render 'shared/stats'
      - unless @users.empty?
        - @users.each do |user|
          = link_to gravatar_for(user, :size => 30), user

/END users/show_follow.html.haml