config/routes.rb
SampleApp::Application.routes.draw do
  resources :password_reminders, :only => [:new, :create] do
    get :reset, :on => :member
  end

  resources :direct_messages, :only => [] do
    get :received, :on => :collection
    get :sent, :on => :collection
  end

  resources :users do
    member do
      get :following, :followers, :confirm, :feed
    end
    resources :feeds, :only => [] do
      get :private, :on => :member
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/recover_password', :to => 'password_reminders#new'
  match '/signup',           :to => 'users#new'
  match '/signin',           :to => 'sessions#new'
  match '/signout',          :to => 'sessions#destroy'
  match '/contact',          :to => 'pages#contact'
  match '/about',            :to => 'pages#about'
  match '/help',             :to => 'pages#help'

  root :to => 'pages#home'

end

app/views/shared/_error_messages.html.haml
/BEGIN shared/error_messages.html.haml

- if object.errors.any?
  #error_explanation
    %h2
      = pluralize(object.errors.count, "error")
      prohibited this
      = object.class.to_s.underscore.humanize.downcase
      from being saved:

    %p There were problems with the following fields:

    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

/END shared/error_messages.html.haml

app/views/shared/_feed.html.haml
/BEGIN shared/_feed.html.haml

- unless @feed_items.empty?
  %table.microposts{ :summary => "User microposts" }
    = render :partial => 'shared/feed_item', :collection => @feed_items

  = will_paginate @feed_items

/END shared/_feed.html.haml

app/views/shared/_feed_item.html.haml
/BEGIN shared/_feed_item.html.haml

%tr
  %td.gravatar
    = link_to gravatar_for(feed_item.user), feed_item.user

  %td.micropost
    %span.user= link_to feed_item.user.username, feed_item.user
    %span.content= feed_item.content
    %span.timestamp
      Posted
      = time_ago_in_words(feed_item.created_at)
      ago.



  %td

    = link_to "delete", feed_item, :method => :delete,
                                   :confirm => "You sure?",
                                   :title => feed_item.content










/END shared/_feed_item.html.haml

app/views/shared/_micropost_form.html.haml
/BEGIN shared/_micropost_form.html.haml

= form_for @micropost do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.text_area :content

  .actions
    = f.submit "Submit"

/END shared/_micropost_form.html.haml

app/views/shared/_stats.html.haml
/BEGIN shared/_stats.html.haml

- @user ||= current_user
.stats
  %table{:summary => "User stats"}
    %tr
      %td
        %a{ :href => "#{following_user_path(@user)}" }
          %span.stat#following
            = "#{@user.following.count} following"
      %td
        %a{ :href => "#{followers_user_path(@user)}" }
          %span.stat#followers
            = pluralize(@user.followers.count, "follower")

/END shared/_stats.html.haml

app/views/shared/_user_info.html.haml
/BEGIN shared/_user_info.html.haml

.user_info
  %a{ :href => "#{ user_path(current_user) }"}
    = gravatar_for current_user, :size => 30
    %span.user_name
      = current_user.name
    %span.microposts
      = pluralize(current_user.microposts.count, "micropost")

/END shared/_user_info.html.haml