config/routes.rb
SampleApp::Application.routes.draw do
  resources :password_reminders, :only => [:new, :create] do
    get :reset, :on => :member
  end

  resources :direct_messages, :only => [] do
    get :received, :on => :collection
    get :sent, :on => :collection
  end

  resources :users do
    member do
      get :following, :followers, :confirm, :feed
    end
    resources :feeds, :only => [] do
      get :private, :on => :member
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/recover_password', :to => 'password_reminders#new'
  match '/signup',           :to => 'users#new'
  match '/signin',           :to => 'sessions#new'
  match '/signout',          :to => 'sessions#destroy'
  match '/contact',          :to => 'pages#contact'
  match '/about',            :to => 'pages#about'
  match '/help',             :to => 'pages#help'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.haml
/BEGIN layouts/_footer.html.haml

%footer
  %nav.round
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path


/END layouts/_footer.html.haml

app/views/layouts/_header.html.haml
/BEGIN layouts/_header.html.haml

%header
  = link_to logo, root_path
  %nav.round
    %ul
      %li= link_to "Home", root_path

      - if signed_in?
        %li= link_to "Users", users_path
        %li= link_to "Profile", current_user
        %li= link_to "Direct Messages", received_direct_messages_path
        %li= link_to "Settings", edit_user_path(current_user)

      %li= link_to "Help", help_path

      - if signed_in?
        %li= link_to "Sign out", signout_path, :method => :delete
      - else
        %li= link_to "Sign in", signin_path

/END layouts/_header.html.haml

app/views/layouts/_stylesheets.html.haml
/BEGIN layouts/_stylesheets.html.haml

/[if lt IE 9]
  %script{ :src => "http://html5shiv.googlecode.com/svn/trunk/html5.js" }

= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print',  :media => 'print'

/[if lt IE 8]
  = stylesheet_link_tag 'blueprint/ie'

= stylesheet_link_tag 'custom', :media => 'screen'

/END layouts/_stylesheets.html.haml

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= title
    = csrf_meta_tag
    = render 'layouts/stylesheets'
    = javascript_include_tag :defaults

  %body
    .container
      = render 'layouts/header'

      %section.round
        - flash.each do |key, value|
          %div{ :class => "flash #{key}" }
            = value
        = yield

      = render 'layouts/footer'
      = debug(params) if Rails.env.development?